// Generated by scripts/water-zones/export-occluders.py from installed native scenes.
using UnityEngine;
namespace FishingMod {
internal static class FishingNativeWaterOccluders {
internal static readonly FishingNativeWaterOccluder[] All = {
new FishingNativeWaterOccluder("Roads/Intersections/BridgeConection/BridgeConnectionGroundPlane",15,false,false,new Vector3(-1507.375f,0.300000004f,-1240f),new Vector3(842.709961f,0.000113246841f,1500f)),
new FishingNativeWaterOccluder("Roads/DrivingPlane",10,false,false,new Vector3(-1541.29999f,1.10000541f,-1168.02718f),new Vector3(736.912804f,1.80007583f,1005.05676f)),
new FishingNativeWaterOccluder("Ground (don't remove pls)",10,true,false,new Vector3(-1781.54071f,-0.271306284f,-1352f),new Vector3(880.293746f,0.562612452f,1015.92707f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (3)",15,false,true,new Vector3(-2982.30005f,0.0500000007f,-1069.40002f),new Vector3(393.192009f,3.87478954e-05f,240.316892f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (9)",15,false,true,new Vector3(-2765.92383f,0.0500000007f,-1680.78369f),new Vector3(375.218719f,1.85170967e-05f,137.818225f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (1)",15,false,true,new Vector3(-2011.73001f,0.170007452f,-1240.05902f),new Vector3(165.999812f,0.250105428f,1500.00004f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (8)",15,false,true,new Vector3(-2893.53589f,0.0500000007f,-1629.51282f),new Vector3(580.654236f,1.48505899e-05f,110.529312f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (7)",15,false,true,new Vector3(-3289.94385f,0.0500000007f,-1645.29663f),new Vector3(231.354187f,1.90919638e-05f,142.096821f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (5)",15,false,true,new Vector3(-3019.01831f,0.0500000007f,-1315.0862f),new Vector3(819.54541f,6.99103228e-05f,520.325448f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (6)",15,false,true,new Vector3(-3455.14233f,0.0500000007f,-1468.72266f),new Vector3(63.8403168f,2.16911094e-05f,161.441626f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (4)",15,false,true,new Vector3(-2548.15234f,0.0500000007f,-1110.37f),new Vector3(562.016907f,9.07839438e-05f,675.682708f)),
new FishingNativeWaterOccluder("TheHamptons/Roads/RoadGroundPlane (2)",15,false,true,new Vector3(-2333.63431f,0.0500000007f,-1316.24609f),new Vector3(474.844574f,0.000146106531f,1087.4352f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (9)",10,true,false,new Vector3(-2885.4962f,-1f,-1038.97859f),new Vector3(178.500228f,0.562612534f,169.766439f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (3)",10,true,false,new Vector3(-3019.01831f,-1f,-1323.41394f),new Vector3(819.54541f,0.562612534f,503.654327f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (7)",10,true,false,new Vector3(-2765.92383f,-1f,-1680.78369f),new Vector3(375.218719f,0.562612534f,137.818237f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (5)",10,true,false,new Vector3(-3289.94385f,-1f,-1645.29663f),new Vector3(231.354202f,0.562612534f,142.096802f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (4)",10,true,false,new Vector3(-3455.14233f,-1f,-1468.72266f),new Vector3(63.8403206f,0.562612534f,161.441544f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground",10,true,false,new Vector3(-2328.98047f,-1f,-1316.24609f),new Vector3(484.173218f,0.562612534f,1087.43506f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (6)",10,true,false,new Vector3(-2893.53589f,-1f,-1629.51282f),new Vector3(580.654236f,0.562612534f,110.529251f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (1)",10,true,false,new Vector3(-3094.08465f,-1f,-1104.64556f),new Vector3(169.62278f,0.562612534f,169.825785f)),
new FishingNativeWaterOccluder("TheHamptons/HamptonsGroundPlanes/Ground (2)",10,true,false,new Vector3(-2548.15234f,-1f,-1110.37f),new Vector3(562.016907f,0.562612534f,675.682617f)),
};
}}
